Repository Hanghae-BnB/HanghaeBnb-BE, pull requests merged in 2023-03, with the labels that each got.

#26 Feat/create house
  src/main/java/com/sparta/hanghaebnb/config/WebSecurityConfig.java
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/dto/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/entity/Facility.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/entity/User.java
  src/main/java/com/sparta/hanghaebnb/entity/WishList.java
  src/main/java/com/sparta/hanghaebnb/healthcheck/HealthCheck.java
  src/main/java/com/sparta/hanghaebnb/repository/HouseRepository.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
Labels: enhancement

#28 feat : 게시글 상세 조회 기능 구현 #19
  src/main/java/com/sparta/hanghaebnb/config/RedisConfig.java
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
Labels: enhancement

#31 Feat : 추가 refresh token 적용 close #30
  src/main/java/com/sparta/hanghaebnb/controller/UserController.java
  src/main/java/com/sparta/hanghaebnb/entity/RefreshToken.java
  src/main/java/com/sparta/hanghaebnb/jwt/JwtUtil.java
  src/main/java/com/sparta/hanghaebnb/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
Labels: enhancement

#32 feat : 게시글 삭제 기능 구현
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
Labels: enhancement

#36 Fix : 리뷰작성 로직 수정 #35
  src/main/java/com/sparta/hanghaebnb/controller/ReviewController.java
  src/main/java/com/sparta/hanghaebnb/dto/MessageResponseDto.java
  src/main/java/com/sparta/hanghaebnb/service/ReviewService.java
Labels: enhancement

#38 Feat : WishListAndHouse 엔티티 구현 #37
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/entity/WishList.java
  src/main/java/com/sparta/hanghaebnb/entity/WishListAndHouse.java
Labels: enhancement, fix

#39 Fix : 게시글 작성 시 S3 이미지 업로드 #34
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/S3Uploader.java
Labels: enhancement, fix

#41 Feat : 카테고리 별 여행지 조회 기능 구현 #40
  src/main/java/com/sparta/hanghaebnb/config/WebSecurityConfig.java
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/repository/HouseRepository.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/S3Uploader.java
Labels: enhancement

#45 Feat : 위시리스트 삭제 로직 추가 #13
  src/main/java/com/sparta/hanghaebnb/controller/WishListController.java
  src/main/java/com/sparta/hanghaebnb/service/WishListService.java
Labels: enhancement

#48 Fix : house category, houseCase 필드 통일 #47
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/dto/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/repository/HouseRepository.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
Labels: fix

#51 Refactor : 예외처리 #15
  src/main/java/com/sparta/hanghaebnb/config/WebSecurityConfig.java
  src/main/java/com/sparta/hanghaebnb/controller/UserController.java
  src/main/java/com/sparta/hanghaebnb/dto/MessageResponseDto.java
  src/main/java/com/sparta/hanghaebnb/exception/CustomException.java
  src/main/java/com/sparta/hanghaebnb/exception/ErrorCode.java
  src/main/java/com/sparta/hanghaebnb/exception/ErrorResponse.java
  src/main/java/com/sparta/hanghaebnb/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/hanghaebnb/jwt/JwtUtil.java
  src/main/java/com/sparta/hanghaebnb/response/ApiResponse.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/ReviewService.java
  src/main/java/com/sparta/hanghaebnb/service/S3Uploader.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
  src/main/java/com/sparta/hanghaebnb/service/WishListService.java
Labels: enhancement, refactor

#54 Fix : 전체 조회 기능 관련 거리 데이터 추가 응답하기 #53
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/controller/ReviewController.java
  src/main/java/com/sparta/hanghaebnb/controller/UserController.java
  src/main/java/com/sparta/hanghaebnb/controller/WishListController.java
  src/main/java/com/sparta/hanghaebnb/dto/request/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/dto/request/LoginRequestDto.java
  src/main/java/com/sparta/hanghaebnb/dto/request/ReviewRequestDto.java
  src/main/java/com/sparta/hanghaebnb/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/HouseResponseDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/LoginResponseDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/MessageResponseDto.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/entity/Review.java
  src/main/java/com/sparta/hanghaebnb/entity/User.java
  src/main/java/com/sparta/hanghaebnb/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/hanghaebnb/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/hanghaebnb/response/ApiResponse.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/ReviewService.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
  src/main/java/com/sparta/hanghaebnb/service/WishListService.java
Labels: fix, refactor

#60 fix : house 도메인 관련 Pathvariable 명 변경
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/controller/WishListController.java
Labels: fix

#66 Refactor : refresh 메서드 수정
  src/main/java/com/sparta/hanghaebnb/controller/UserController.java
  src/main/java/com/sparta/hanghaebnb/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/hanghaebnb/entity/RefreshToken.java
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
Labels: fix, refactor

#70 Feat: review 삭제 추가
  src/main/java/com/sparta/hanghaebnb/controller/ReviewController.java
  src/main/java/com/sparta/hanghaebnb/exception/ErrorCode.java
  src/main/java/com/sparta/hanghaebnb/repository/ReviewRepository.java
  src/main/java/com/sparta/hanghaebnb/service/ReviewService.java
Labels: enhancement

#71 Fix: exception 수정
  src/main/java/com/sparta/hanghaebnb/controller/ReviewController.java
  src/main/java/com/sparta/hanghaebnb/exception/ErrorCode.java
  src/main/java/com/sparta/hanghaebnb/service/S3Uploader.java
Labels: fix, refactor

#73 Feat/house valud
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/dto/request/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/exception/ErrorCode.java
  src/main/java/com/sparta/hanghaebnb/exception/GlobalExceptionHandler.java
Labels: enhancement, fix

#75 Feat : 게시물 도메인 이미지 리사이징 #74
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/dto/request/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/main/java/com/sparta/hanghaebnb/service/S3Uploader.java
Labels: enhancement

#76 Feat : access토큰 자동 발급 구현
  src/main/java/com/sparta/hanghaebnb/config/WebSecurityConfig.java
  src/main/java/com/sparta/hanghaebnb/entity/RefreshToken.java
  src/main/java/com/sparta/hanghaebnb/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/hanghaebnb/jwt/JwtUtil.java
Labels: fix

#77 Fix : refresh 메서드 제거
  src/main/java/com/sparta/hanghaebnb/service/UserService.java
Labels: fix

#81 Fix : 상세 페이지 관련 응답데이터 추가
  src/main/java/com/sparta/hanghaebnb/controller/HouseController.java
  src/main/java/com/sparta/hanghaebnb/dto/request/HouseRequestDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/FacilityResponseDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/HouseDetailResponseDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/HouseResponseDto.java
  src/main/java/com/sparta/hanghaebnb/dto/response/ReviewResponseDto.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/repository/ReviewRepository.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
  src/test/java/com/sparta/hanghaebnb/testcase/TestCase.java
Labels: fix

#83 Refactor : 연관관계 편의메서드 변경 #82
  src/main/java/com/sparta/hanghaebnb/entity/Facility.java
  src/main/java/com/sparta/hanghaebnb/entity/House.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
Labels: fix

#90 Fix: 리뷰, 별점 수정 #89
  src/main/java/com/sparta/hanghaebnb/dto/response/HouseResponseDto.java
  src/main/java/com/sparta/hanghaebnb/repository/HouseRepository.java
  src/main/java/com/sparta/hanghaebnb/service/HouseService.java
Labels: enhancement
